const CATEGORIES = ['general', 'code', 'webdev', 'image', 'music', 'video', 'voice', 'humanizer', 'allinone', 'presentations', 'travel', 'automation', 'ragstack', 'privacy'];

const I18N = {
  es: {
    title: "Marcadores de IA",
    subtitle: "Mi selección de herramientas de IA gratuitas o freemium. Probadas y recomendadas.",
    search: "Buscar herramientas...",
    noResults: "No se encontraron marcadores que coincidan con tu búsqueda.",
    noFavorites: "Aún no tienes favoritos. Pulsa ♥ en cualquier herramienta.",
    open: "Visitar sitio",
    suggest: "sugerir herramienta",
    buildStack: "arma tu stack",
    favorites: "favoritos",
    pricing: "precio",
    categories: "categorías",
    tools: "herramientas",
    cat: { all: "todos", general: "general", code: "código", webdev: "webdev", image: "imagen", music: "música", video: "video", voice: "voz", humanizer: "humanizador", allinone: "muchos en uno", presentations: "presentaciones", travel: "viajes", automation: "automatizaciones", ragstack: "rag stack", privacy: "privacidad" },
    price: { all: "todas", free: "gratis", freemium: "limitado" },
    newLabel: "nuevo",
    sortLabel: "ordenar",
    sort: { default: "por defecto", az: "A–Z", newest: "más nuevas", recommended: "recomendadas" },
    stackRestart: "empezar de nuevo",
    stackResult: "tu stack",
    stackEmpty: "No hay coincidencias. Prueba a relajar los filtros.",
    qUsecase: "¿Qué quieres hacer?",
    qPricing: "¿Qué precio te va?",
    qLevel: "¿Cuánto sabes de tecnología?",
    uc: { content: "Crear contenido (video, imagen, música)", code: "Programar o hacer webs", automate: "Automatizar tareas", research: "Investigar o aprender", present: "Crear presentaciones", travel: "Planificar viajes", privacy: "Proteger mi privacidad" },
    pp: { free: "Solo herramientas gratuitas", any: "Freemium también me vale" },
    lvl: { basic: "Lo básico", advanced: "Me manejo bien" },
    footer: "Marcadores de IA · 2026 · made by iamLudok"
  },
  en: {
    title: "AI Bookmarks",
    subtitle: "My selection of free or freemium AI tools. Tested and recommended.",
    search: "Search tools...",
    noResults: "No bookmarks found matching your search.",
    noFavorites: "No favorites yet. Press ♥ on any tool.",
    open: "Visit site",
    suggest: "suggest tool",
    buildStack: "build your stack",
    favorites: "favorites",
    pricing: "pricing",
    categories: "categories",
    tools: "tools",
    cat: { all: "all", general: "general", code: "code", webdev: "webdev", image: "image", music: "music", video: "video", voice: "voice", humanizer: "humanizer", allinone: "all-in-one", presentations: "presentations", travel: "travel", automation: "automation", ragstack: "rag stack", privacy: "privacy" },
    price: { all: "all", free: "free", freemium: "limited" },
    newLabel: "new",
    sortLabel: "sort",
    sort: { default: "default", az: "A–Z", newest: "newest", recommended: "recommended" },
    stackRestart: "start over",
    stackResult: "your stack",
    stackEmpty: "No matches. Try relaxing the filters.",
    qUsecase: "What do you want to do?",
    qPricing: "What pricing works for you?",
    qLevel: "How tech-savvy are you?",
    uc: { content: "Create content (video, image, music)", code: "Code or build websites", automate: "Automate tasks", research: "Research or learn", present: "Create presentations", travel: "Plan trips", privacy: "Protect my privacy" },
    pp: { free: "Free tools only", any: "Freemium is fine too" },
    lvl: { basic: "Basic level", advanced: "Pretty comfortable" },
    footer: "AI Bookmarks · 2026 · made by iamLudok"
  },
  eu: {
    title: "AA Laster-markak",
    subtitle: "Nire AA tresna doako edo freemium hautapena. Probatutakoak eta gomendatuak.",
    search: "Tresnak bilatu...",
    noResults: "Ez da zure bilaketarekin bat datorren laster-markarik aurkitu.",
    noFavorites: "Ez duzu gogokoerik oraindik. Sakatu ♥ edozein tresnan.",
    open: "Gunea bisitatu",
    suggest: "tresna iradoki",
    buildStack: "zure stack-a eraiki",
    favorites: "gogokoak",
    pricing: "prezioa",
    categories: "kategoriak",
    tools: "tresna",
    cat: { all: "denak", general: "orokorra", code: "kodea", webdev: "webdev", image: "irudia", music: "musika", video: "bideoa", voice: "ahotsa", humanizer: "humanizatzailea", allinone: "asko batean", presentations: "aurkezpenak", travel: "bidaiak", automation: "automatizazioak", ragstack: "rag stack", privacy: "pribatutasuna" },
    price: { all: "denak", free: "doakoa", freemium: "mugatua" },
    newLabel: "berria",
    sortLabel: "ordenatu",
    sort: { default: "lehenetsia", az: "A–Z", newest: "berriak", recommended: "gomendatuak" },
    stackRestart: "berriro hasi",
    stackResult: "zure stack-a",
    stackEmpty: "Ez dago paraderik. Iragazkiak lasaitu.",
    qUsecase: "Zer egin nahi duzu?",
    qPricing: "Zer prezio nahiago duzu?",
    qLevel: "Zenbat dakizu teknologiaz?",
    uc: { content: "Edukia sortu (bideoa, irudia, musika)", code: "Programatu edo webak eraiki", automate: "Atazak automatizatu", research: "Ikertu edo ikasi", present: "Aurkezpenak sortu", travel: "Bidaiak planifikatu", privacy: "Nire pribatutasuna babestu" },
    pp: { free: "Tresna doakoak soilik", any: "Freemium ere ondo" },
    lvl: { basic: "Oinarrizko maila", advanced: "Ondo moldatzen naiz" },
    footer: "AA Laster-markak · 2026 · made by iamLudok"
  }
};

const BOOKMARKS = [
  { title: "ChatGPT", url: "https://chat.openai.com", cat: ["general"], pricing: "freemium", desc: { es: "El clásico. Perfecto para cualquier cosa: escribir, investigar, resolver dudas. El más versátil.", en: "The classic. Perfect for anything: writing, research, solving questions. The most versatile.", eu: "Klasikoa. Edozer gauzetarako ezin hobea: idatzi, ikertu, zalantzak argitu. Polifazetikoena." }},
  { title: "Perplexity", url: "https://perplexity.ai", cat: ["general"], pricing: "freemium", desc: { es: "Como Google pero te da la respuesta directa con fuentes. Ideal para investigar rápido.", en: "Like Google but gives you the direct answer with sources. Ideal for quick research.", eu: "Google bezala baina erantzun zuzena ematen dizu ituriekin. Azkar ikertzeko aproposa." }},
  { title: "NotebookLM", url: "https://notebooklm.google/", cat: ["general"], pricing: "free", desc: { es: "El asistente de Google para investigar. Sube PDFs, webs o textos y te genera resúmenes, respuestas y hasta podcasts.", en: "Google's research assistant. Upload PDFs, websites or texts and it generates summaries, answers and even podcasts.", eu: "Googleren ikerketa-laguntzailea. Igo PDFak, webak edo testuak eta laburpenak, erantzunak eta baita podcastak ere sortzen dizkizu." }},
  { title: "Gemini", url: "https://gemini.google.com/app", cat: ["general"], pricing: "freemium", desc: { es: "El asistente de Google. Potente para investigar, escribir y razonar. Integrado con el ecosistema Google.", en: "Google's assistant. Powerful for research, writing and reasoning. Integrated with the Google ecosystem.", eu: "Googleren laguntzailea. Indartsua ikertzeko, idazteko eta arrazoitzeko. Google ekosistemarekin integratua." }},
  { title: "Claude", url: "https://claude.ai", cat: ["code"], pricing: "freemium", recommended: true, desc: { es: "Mi favorito para programar. Entiende el contexto mejor que nadie y no se pierde en proyectos grandes.", en: "My favorite for coding. Understands context better than anyone and doesn't get lost in big projects.", eu: "Nire gogokoena programatzeko. Testuingurua inork baino hobeto ulertzen du eta ez da galtzen proiektu handietan." }},
  { title: "Opencode", url: "https://opencode.ai", cat: ["code"], pricing: "free", desc: { es: "Agente de código en terminal. Open source y con soporte para múltiples modelos de IA.", en: "Terminal-based coding agent. Open source with support for multiple AI models.", eu: "Kode-agentea terminalean. Kode irekia eta AA eredu anitzentzako euskarriarekin." }},
  { title: "GitHub Copilot", url: "https://github.com/features/copilot", cat: ["code"], pricing: "freemium", desc: { es: "El copiloto de GitHub para programar. Autocompletado inteligente y sugerencias de código directamente en tu editor.", en: "GitHub's coding copilot. Smart autocompletion and code suggestions directly in your editor.", eu: "GitHuben kode-kopilotua. Autoosaketa adimentsua eta kode-iradokizunak zuzenean zure editorean." }},
  { title: "Lovable", url: "https://lovable.dev", cat: ["webdev"], pricing: "freemium", desc: { es: "El más fácil para empezar. En minutos tienes algo funcional y bonito sin tocar código.", en: "In minutes you have something functional and beautiful without touching code.", eu: "Hasteko errazena. Minututan zerbait funtzionala eta polita duzu koderik ukitu gabe." }},
  { title: "Bubble", url: "https://bubble.io", cat: ["webdev"], pricing: "freemium", desc: { es: "Más complejo pero muy potente. Para apps serias sin saber programar.", en: "More complex but very powerful. For serious apps without knowing how to code.", eu: "Konplexuagoa baina oso indartsua. App serioetarako programatzen jakin gabe." }},
  { title: "v0", url: "https://v0.dev", cat: ["webdev"], pricing: "freemium", desc: { es: "Mi favorito para crear aplicaciones mediante lenguaje natural.", en: "My favorite for creating applications using natural language.", eu: "Nire gogokoena aplikazioak hizkuntza naturalaren bidez sortzeko." }},
  { title: "Bolt", url: "https://bolt.new", cat: ["webdev"], pricing: "freemium", desc: { es: "Rápido para prototipos. Se queda corto en proyectos grandes pero para empezar va genial.", en: "Fast for prototypes. Falls short on big projects but great for starting out.", eu: "Azkarra prototipoetarako. Proiektu handietan motz geratzen da baina hasteko bikaina." }},
  { title: "Replit", url: "https://replit.com", cat: ["webdev"], pricing: "freemium", desc: { es: "Una de las mejores para vibe coding: fluidez, ritmo y ganas de crear.", en: "One of the best for vibe coding: flow, rhythm and the desire to create.", eu: "Vibe coding-erako tresnarik onenetakoa, jariakortasuna eta sortzeko gogoa bilatzen duzunean." }},
  { title: "Make", url: "https://www.make.com", cat: ["automation"], pricing: "freemium", desc: { es: "Automatiza flujos de trabajo conectando apps sin código. Ideal para integrar servicios y crear procesos automáticos.", en: "Automate workflows by connecting apps without code. Ideal for integrating services and creating automatic processes.", eu: "Lan-fluxuak automatizatzen ditu appak koderik gabe konektatuz. Zerbitzuak integratzeko aproposa." }},
  { title: "Zapier", url: "https://zapier.com", cat: ["automation"], pricing: "freemium", desc: { es: "El veterano de las automatizaciones. Conecta miles de apps y crea flujos automáticos en minutos.", en: "The veteran of automation. Connect thousands of apps and create automatic workflows in minutes.", eu: "Automatizazioen beteranoa. Milaka app konektatzen ditu eta fluxu automatikoak sortzen minututan." }},
  { title: "N8N", url: "https://n8n.io", cat: ["automation"], pricing: "freemium", desc: { es: "Automatización open source y self-hosteable. Flujos visuales con lógica avanzada y cientos de integraciones.", en: "Open source and self-hostable automation. Visual workflows with advanced logic and hundreds of integrations.", eu: "Automatizazio kode irekia eta self-hosteable. Fluxu bisualak logika aurreratuarekin." }},
  { title: "Napkin", url: "https://app.napkin.ai", cat: ["image"], pricing: "freemium", desc: { es: "Convierte texto en diagramas e infografías automáticamente. Perfecto para visualizar ideas rápidamente.", en: "Converts text into diagrams and infographics automatically. Perfect for visualizing ideas quickly.", eu: "Testua diagrama eta infografietan bihurtzen du automatikoki. Ideiak azkar bistaratzeko ezin hobea." }},
  { title: "Suno", url: "https://suno.ai", cat: ["music"], pricing: "freemium", desc: { es: "Creas canciones completas con solo describirlas. Los resultados sorprenden bastante.", en: "Create complete songs just by describing them. The results are quite surprising.", eu: "Abesti osoak sortzen dituzu deskribatzearekin soilik. Emaitzek nahiko harritu egiten dute." }},
  { title: "Udio", url: "https://udio.com", cat: ["music"], pricing: "freemium", desc: { es: "Alternativa a Suno con mejor calidad de audio según algunos. Vale la pena probarlo.", en: "Alternative to Suno with better audio quality according to some. Worth trying.", eu: "Sunoren alternatiba audio kalitate hobearekin batzuen arabera. Probatzea merezi du." }},
  { title: "Runway", url: "https://runwayml.com", cat: ["video"], pricing: "freemium", desc: { es: "El más conocido para video. Efectos visuales impresionantes y fácil de usar.", en: "The most well-known for video. Impressive visual effects and easy to use.", eu: "Bideorako ezagunena. Efektu bisual ikusgarriak eta erraz erabiltzekoa." }},
  { title: "Pika", url: "https://pika.art", cat: ["video"], pricing: "freemium", desc: { es: "Videos cortos con estilo más artístico. Bueno para contenido creativo y diferente.", en: "Short videos with a more artistic style. Good for creative and different content.", eu: "Bideo laburrak estilo artistikoagoarekin. Eduki sortzaile eta ezberdinerako ona." }},
  { title: "Veed", url: "https://www.veed.io/", cat: ["video"], pricing: "freemium", desc: { es: "Editor de video online con IA. Subtítulos automáticos, recortes y efectos sin instalar nada.", en: "Online video editor with AI. Automatic subtitles, trimming and effects without installing anything.", eu: "Lineako bideo-editorea AArekin. Azpitituluak automatikoak ezer instalatu gabe." }},
  { title: "HeyGen", url: "https://app.heygen.com/", cat: ["video"], pricing: "freemium", desc: { es: "Crea videos con avatares realistas que hablan por ti. Ideal para presentaciones sin ponerte delante de la cámara.", en: "Create videos with realistic avatars that speak for you. Ideal for presentations without being on camera.", eu: "Avatar errealistekin bideoak sortzen ditu. Kameraren aurrean jarri gabe edukia sortzeko aproposa." }},
  { title: "Narakeet", url: "https://narakeet.com", cat: ["video", "voice"], pricing: "freemium", recommended: true, desc: { es: "Voces muy naturales en muchos idiomas. Lo uso para narrar videos sin grabar.", en: "Very natural voices in many languages. I use it to narrate videos without recording.", eu: "Ahots oso naturalak hizkuntza askotan. Bideoak grabatu gabe kontatzeko erabiltzen dut." }},
  { title: "ElevenLabs", url: "https://elevenlabs.io", cat: ["voice", "music"], pricing: "freemium", desc: { es: "La mejor calidad de voz sintética. Clona voces, genera audio hiperrealista, crea canciones y efectos de sonido.", en: "The best synthetic voice quality. Clone voices, generate hyperrealistic audio, create songs and sound effects.", eu: "Ahots sintetikoaren kalitaterik onena. Ahotsak klonatzen ditu, audio hiperrealista sortzen." }},
  { title: "Tenorshare AI", url: "https://ai.tenorshare.com/products/ai-bypass", cat: ["humanizer"], pricing: "freemium", desc: { es: "Hace que textos de IA pasen desapercibidos. Útil si necesitas que suene más natural.", en: "Makes AI texts go unnoticed. Useful if you need it to sound more natural.", eu: "AA testuak oharkabean pasarazten ditu. Baliagarria naturalago entzun behar bada." }},
  { title: "Genspark", url: "https://www.genspark.ai/", cat: ["allinone"], pricing: "freemium", desc: { es: "Motor de búsqueda con IA que combina múltiples LLMs. Su Super Agent automatiza tareas complejas: crea slides, documentos, e incluso hace llamadas por ti.", en: "AI search engine combining multiple LLMs. Its Super Agent automates complex tasks: creates slides, documents, and even makes phone calls for you.", eu: "LLM anitz konbinatzen dituen AA bilaketa-motorra. Bere Super Agentek ataza konplexuak automatizatzen ditu." }},
  { title: "ChatHub", url: "https://app.chathub.gg/", cat: ["allinone"], pricing: "free", desc: { es: "Todos los modelos en un solo lugar. Perfecto para comparar respuestas lado a lado.", en: "All models in one place. Perfect for comparing responses side by side.", eu: "Eredu guztiak toki bakarrean. Erantzunak elkarren ondoan konparatzeko ezin hobea." }},
  { title: "LMArena", url: "https://lmarena.ai", cat: ["allinone"], pricing: "free", desc: { es: "Pruebas a ciegas entre modelos. Interesante para ver cuál prefieres sin saber cuál es cuál.", en: "Blind tests between models. Interesting to see which one you prefer without knowing which is which.", eu: "Ereduen arteko proba itsuak. Interesgarria zein nahiago duzun ikusteko." }},
  { title: "Google AI Studio", url: "https://aistudio.google.com", cat: ["allinone"], pricing: "free", desc: { es: "Herramienta oficial de Google para usar sus modelos de IA como Gemini.", en: "Google's official tool to use their AI models like Gemini.", eu: "Googleren tresna ofiziala bere AA ereduak erabiltzeko, hala nola Gemini." }},
  { title: "HuggingFace Spaces", url: "https://huggingface.co/spaces", cat: ["allinone"], pricing: "free", desc: { es: "Miles de modelos para probar gratis. El playground definitivo para explorar IA.", en: "Thousands of models to try for free. The ultimate playground for exploring AI.", eu: "Milaka eredu doan probatzeko. AA esploratzeko jolasleku definitiboa." }},
  { title: "Gamma", url: "https://gamma.app", cat: ["presentations"], pricing: "freemium", desc: { es: "Presentaciones en segundos. Le dices el tema y te genera algo presentable al instante.", en: "Presentations in seconds. You tell it the topic and it generates something presentable instantly.", eu: "Aurkezpenak segundotan. Gaia esaten diozu eta berehala zerbait aurkezgarria sortzen du." }},
  { title: "Visme", url: "https://visme.co", cat: ["presentations"], pricing: "freemium", desc: { es: "Más control sobre el diseño que Gamma. Para cuando quieres algo más personalizado.", en: "More control over design than Gamma. For when you want something more customized.", eu: "Gammak baino kontrol gehiago diseinuan. Zerbait pertsonalizatuagoa nahi duzunerako." }},
  { title: "PPT", url: "https://ppt.ai/", cat: ["presentations"], pricing: "freemium", desc: { es: "Storytelling visual con IA. Crea presentaciones narrativas con un estilo moderno y atractivo.", en: "Visual storytelling with AI. Create narrative presentations with a modern and attractive style.", eu: "Storytelling bisuala AArekin. Aurkezpen narratiboak sortzen ditu estilo moderno eta erakargarriarekin." }},
  { title: "Vacay Chatbot", url: "https://usevacay.com", cat: ["travel"], pricing: "free", desc: { es: "Te arma itinerarios completos en segundos. Sorprendentemente útil para planificar.", en: "Builds complete itineraries in seconds. Surprisingly useful for planning.", eu: "Ibilbide osoak segundotan prestatzen dizkizu. Harrigarriro baliagarria planifikatzeko." }},
  { title: "GuideGeek", url: "https://guidegeek.com", cat: ["travel"], pricing: "free", desc: { es: "Como tener un guía local que te responde cualquier duda sobre tu destino.", en: "Like having a local guide who answers any question about your destination.", eu: "Bertako gida bat izatea bezala, zure helmugari buruzko edozein zalantza erantzuten dizuna." }},
  { title: "Curiosio", url: "https://curiosio.com", cat: ["travel"], pricing: "free", desc: { es: "Especializado en road trips. Te sugiere rutas alternativas y lugares que no conocías.", en: "Specialized in road trips. Suggests alternative routes and places you didn't know.", eu: "Road trip-etan espezializatua. Ibilbide alternatiboak eta ezagutzen ez zenituen lekuak iradokitzen dizkizu." }},
  { title: "LangChain", url: "https://www.langchain.com/", cat: ["ragstack"], pricing: "free", desc: { es: "Framework open source para construir aplicaciones con LLMs. Conecta modelos, herramientas y datos para crear agentes y flujos de IA.", en: "Open source framework for building applications with LLMs. Connect models, tools and data to create AI agents and workflows.", eu: "LLMekin aplikazioak eraikitzeko kode irekiko frameworka. Ereduak, tresnak eta datuak konektatzen ditu." }},
  { title: "LangSmith", url: "https://smith.langchain.com/", cat: ["ragstack"], pricing: "freemium", desc: { es: "Plataforma para evaluar, monitorizar y depurar aplicaciones con LLMs. Imprescindible para medir la calidad de tus agentes.", en: "Platform for evaluating, monitoring and debugging LLM applications. Essential for measuring the quality of your agents.", eu: "LLM aplikazioak ebaluatu, monitorizatu eta arazteko plataforma. Ezinbestekoa zure agenteen kalitatea neurtzeko." }},
  { title: "CrewAI", url: "https://www.crewai.com/", cat: ["ragstack"], pricing: "freemium", desc: { es: "Framework para crear equipos de agentes de IA que colaboran entre sí. Define roles, tareas y flujos para resolver problemas complejos.", en: "Framework for creating teams of AI agents that collaborate with each other. Define roles, tasks and workflows to solve complex problems.", eu: "Elkarrekin lankidetzan aritzen diren AA agente taldeak sortzeko frameworka." }},
  { title: "Ollama", url: "https://ollama.com", cat: ["privacy", "ragstack"], pricing: "free", recommended: true, addedAt: "2026-05-07", desc: { es: "Ejecuta modelos de IA en tu propia máquina. Tus datos no salen a ningún servidor. La alternativa privada a ChatGPT para quien no quiere que nadie lea sus conversaciones.", en: "Run AI models on your own machine. Your data never leaves your computer. The private alternative to ChatGPT for those who don't want anyone reading their conversations.", eu: "AA ereduak zure makinan exekutatzen ditu. Zure datuak ez dira inongo zerbitzarira joaten." }},
  { title: "Brave Browser", url: "https://brave.com", cat: ["privacy"], pricing: "free", addedAt: "2026-05-07", desc: { es: "Navegador que bloquea rastreadores y anuncios por defecto. Si usas herramientas de IA desde Chrome, Google puede registrar qué buscas. Con Brave, no.", en: "Browser that blocks trackers and ads by default. If you use AI tools from Chrome, Google can log what you search. With Brave, it can't.", eu: "Nabigatzaileak jarraipen-gailuak eta iragarkiak blokeatzen ditu lehenespenez." }},
  { title: "Bitwarden", url: "https://bitwarden.com", cat: ["privacy"], pricing: "free", addedAt: "2026-05-07", desc: { es: "Gestor de contraseñas open source y gratuito. Si usas 20 herramientas de IA con la misma contraseña y una filtra, te hackean todo. Con Bitwarden, cada cuenta tiene su contraseña única.", en: "Free and open source password manager. If you use 20 AI tools with the same password and one leaks, everything gets hacked. With Bitwarden, each account has its own unique password.", eu: "Pasahitz-kudeatzaile doako eta kode irekikoa. Kontu bakoitzak bere pasahitz bakarra du." }},
  { title: "Have I Been Pwned", url: "https://haveibeenpwned.com", cat: ["privacy"], pricing: "free", addedAt: "2026-05-07", desc: { es: "Comprueba si tu correo o contraseña han aparecido en alguna filtración de datos. Si te has registrado en muchas webs de IA, esto es lo primero que deberías mirar.", en: "Check if your email or password has appeared in any data breach. If you've signed up for many AI sites, this is the first thing you should check.", eu: "Egiaztatu zure posta elektronikoa edo pasahitza datu-filtrazio batean agertu den." }},
  { title: "JustDeleteMe", url: "https://justdeleteme.xyz", cat: ["privacy"], pricing: "free", addedAt: "2026-05-07", desc: { es: "Directorio de enlaces directos para eliminar tu cuenta de cientos de servicios web. Clasificados por dificultad.", en: "Directory of direct links to delete your account from hundreds of web services. Rated by difficulty.", eu: "Ehunka web-zerbitzutatik zure kontua ezabatzeko esteka zuzenen direktorioa." }},
  { title: "Google Takeout", url: "https://takeout.google.com", cat: ["privacy"], pricing: "free", addedAt: "2026-05-07", desc: { es: "Descarga todo lo que Google tiene sobre ti: búsquedas, historial de ubicación, YouTube, Gmail, Maps y mucho más.", en: "Download everything Google has on you: searches, location history, YouTube, Gmail, Maps and much more.", eu: "Deskargatu Googlek zuri buruz duen guztia: bilaketak, kokapen-historia, YouTube, Gmail, Maps eta gehiago." }},
  { title: "Google My Activity", url: "https://myactivity.google.com", cat: ["privacy"], pricing: "free", addedAt: "2026-05-07", desc: { es: "Ve y borra tu historial de actividad en Google: qué buscaste, qué viste en YouTube, qué le dijiste al Asistente.", en: "View and delete your Google activity history: what you searched, what you watched on YouTube, what you said to the Assistant.", eu: "Ikusi eta ezabatu zure Google jarduera-historia: zer bilatu zenuen, YouTube-n zer ikusi zenuen." }}
];

const USE_CASE_CATS = {
  content:  ['image', 'video', 'music', 'voice'],
  code:     ['code', 'webdev'],
  automate: ['automation', 'ragstack'],
  research: ['general', 'allinone'],
  present:  ['presentations'],
  travel:   ['travel'],
  privacy:  ['privacy'],
};

function favicon(url, sz = 64) {
  try { return `https://www.google.com/s2/favicons?domain=${new URL(url).hostname}&sz=${sz}`; }
  catch(e) { return ''; }
}

function isNew(addedAt) {
  if (!addedAt) return false;
  return (Date.now() - new Date(addedAt).getTime()) / 86400000 <= 60;
}
